shuaibiyy/awesome-tf

README.md
I would like to add this Terraform module for a rancher server on Digitalocean.
Feedback is always welcome.
=> Adding Terraform module for a rancher server

README.md
Kief's book are blog post are not terraform specific, but I feel like very helpful for anyone with a complex or multi-environment terraform setup.
=> Add terraform registry and some additional links

README.md
Feel free to edit or add more. :)
=> Add some editor plugins

README.md
Add a link to the _How to Build Reusable, Composable, Battle tested Terraform Modules_ presentation by Yevgeniy Brikman (Oct 2017)
=> Add a link to presentation

README.md
Add [terraform-aws-secure-baseline](https://github.com/nozaq/terraform-aws-secure-baseline) to Community Modules.
=> Add terraform-aws-secure-baseline

README.md
=> Update links to AWS VPC and SG modules

README.md
=> Add uptimerobot and healthchecksio providers

README.md
Update the Linode provider to the official one
And adds the Linode k8s module
=> update linode provider and add Linode k8s module

README.md
Added information about some of my Terraform projects.
Also, removed information about modules (previous generation) which are no longer supported by me or were already migrated.
=> Added some of terraform-aws-modules, modules.tf, pre-commit-terraform

README.md
These official [Terraform GitHub Actions](https://github.com/hashicorp/terraform-github-actions) allow you to run terraform fmt, validate and plan on your pull requests to help you review and validate Terraform changes. Similar documentations also on [terraform.io](https://www.terraform.io/docs/github-actions/actions/index.html)
=> Add official Terraform GitHub Actions

README.md
- Add _period(.)_ for consistency
- Add more providers
- Datadog
- DigitalOcean
- Docker
- GitHub
- GitLab
- OpenStack
Quite many providers listed under [Terraform Providers](https://github.com/terraform-providers)
=> Add terraform providers

README.md
Hi, I thought this title might be great addition to your list of resources/videos/books. Thank you for your consideration
=> add Terraform in Action book

README.md
Sort items in the `Community Modules` section in alphabetical order.
No items added or removed.
=> sort community modules in alphabetical order

README.md
Add Checkov, a static analysis tool : https://github.com/bridgecrewio/checkov/
=> add checkov - terraform static analysis tool

README.md
Add [terraform-aws-jenkins-ha-agents](https://github.com/neiman-marcus/terraform-aws-jenkins-ha-agents):
* EC2 Based with autoscaling
* EFS attached
* Spot agents
* Fully customizable.
=> Add jenkins-ha-agents module.

README.md
Hello,
I added my remote state repository as well. 
Hope this is fine. If not let me know what to change :)
Greetings 
Malte
=> Add TerraDepot

README.md
terraform-aws-modules/meta
terraform-cost-estimation
terragrunt-reference-architecture
...
=> Added some more links to projects I work with

README.md
Adding a couple more of my projects.
=> Add serverless.tf and terraform-aws-lambda module

README.md
Added AirIAM from bridge crew, a tool to create least privilege TF code from an IAM policy
=> added airIAM

README.md
Terraform module to create a responsive Maintenance Page using Cloudflare Workers.
=> Add terraform-cloudflare-maintenance

README.md
- Add lint to tf-init-booster tool
=> Add tf-init-booster tool

README.md
Hi!
There are [25+ providers](https://github.com/GoogleCloudPlatform/terraformer/tree/master/providers) which looks very cool, so I've changed few to many 😄
=> Update description for terraformer

README.md
=> Mark tools that do not work with Terraform 0.12.x

README.md
Hi @shuaibiyy,
I am the maintainer of the Terraform generator that is used to scaffold new terraform project/module. Would be great to include this in the awesome list.
=> Added terraform generator with Boilerplates section

README.md
Add [terraform-aws-lambda-auto-package](https://github.com/nozaq/terraform-aws-lambda-auto-package).
=> add terraform-aws-lambda-auto-package

README.md
Added flora tool to awesome list
=> Added flora tool to awesome list

README.md
- added `terraform-operator` to the **`Tools`** section
=> add terraform-operator to the tools list

README.md
- Adding a tutorial on how to write [Open Policy Agent](https://www.openpolicyagent.org/) policies for Terraform
- Adding [Scalr](https://scalr.com), a remote backend for Terraform with Open Policy Agent integration
=> Adding Scalr and an Open Policy Agent tutorial

README.md
Inspire from https://github.com/veggiemonk/awesome-docker, I add a legend for Abandoned, Not compatible and Monetized resources.
I'm not very satisfied with the result.
=> Add legend

README.md
Added clarity to readme. Clarity is a testing framework (gherkin bdd inspired)
=> Added Clarity

README.md
Disclaimer - not my blog, just a very helpful article I came across and thought it belonged in this list
=> Add link to ECS Fargate tutorial

README.md
I have used this provider to great success, the simplicity is its strength, works with almost any manifest.
=> Add banzaicloud-k8s provider

README.md
The project has received updates recently and should probably not flagged as abandonned.
=> Terraform GitHub Actions not abandoned

README.md
=> terraformize

README.md
Add Shisho, a lightweight static analysis tool for Terraform.
https://github.com/flatt-security/shisho
=> Add Shisho

README.md
Adding env0 information as an alternative to Terraform Cloud
=> Update README.md - adding env0 information

README.md
* https://github.com/tfmigrator/cli
* https://github.com/tfmigrator/tfmigrator
Go library and CLI to migrate Terraform Configuration and State.
=> Add tfmigrator

README.md
Add modulehub.io as a private Terraform Module registry
=> Add Modulehub

README.md
add terradozer and update toc
---
cc @shuaibiyy
=> add terradozer, inframap, terracost, terracognita

README.md
Add [Terrastate](https://github.com/rohinivsenthil/terrastate) under tools
=> Add terrastate

README.md
These tools have helped me alot when working with terraform cloud and vault.  I have been able to pull secrets and not have them stored in state.
=> Add terraform-credentials-vault and  tfvaultenv

README.md
- Big Little Book On Terraform
- Deep-Dive Terraform on Azure
- HashiCorp Infrastructure Automation Certification Guide
- Patterns and Practices for Infrastructure as Code: With examples in Python and Terraform
=> books: add some terraform books

README.md
* Removed legacy terraform-community-modules
* Added a couple of links to media projects (YouTube channel and weekly.tf)
@chenrui333 What do you think? :)
=> Yearly update of my Terraform projects

README.md
Adding more Terraform related tools that are created by me..
=> tools: add more Terraform related tools

README.md
https://starchart.cc/cloudposse/atmos
https://github.com/cloudposse/atmos
This is one of my daily tools and it is truly awesome
=> tools: add atmos

README.md
Adding Terrakube Open source tool
=> tools: add Terrakube Open source tool

README.md
https://github.com/suzuki-shunsuke/tfaction
> GitHub Actions collection for Opinionated Terraform Workflow
=> tools: add tfaction

README.md
Add the env0 provider to the list of vendor supported providers.
=> provider: add env0

README.md
Hi there,
Let me share my new project. I’m an author of some third-party tools, which include tfmigrate, tfupdate, hcledit, etc. I'm currently working on a refactoring tool for Terraform.
https://github.com/minamijoyo/tfedit
Although the initial goal of this project is to provide a way for bulk refactoring of the aws_s3_bucket resource required by breaking changes in AWS provider v4, the project scope is not limited to specific use-cases. It's by no means intended to be an upgrade tool for all your providers. Instead of covering all you need, it provides reusable building blocks for Terraform refactoring and shows examples of how to compose them in real-world use-cases.
=> tools: add tfedit

README.md
Discussed in https://github.com/shuaibiyy/awesome-terraform/issues/173.
Maybe we should organize such local communities in a separate block? WDYT?
E.g.
```
- [Telegram (Ukrainian speak community)](https://t.me/terraform_ukraine)
```
?
=> community: add Ukrainian Terraform telegram community

README.md
Added [terraform-provider-sigsci](https://github.com/signalsciences/terraform-provider-sigsci)
=> provider: add sigsci

README.md
Hello Shuaib, it's a great list. I wanted to put TPI into this list, because terraform community would like it. 
Best regards...
=> Add TPI - Terraform Iterative Provider

README.md
Pike is an opensource  tool I created to determine permission required to build your terraform.
=> Pike is for determining permission required to build Terraform

README.md
add Tool > aws2tf link and description
=> Update README.md / add Tool > aws2tf

README.md
https://github.com/dineshba/tf-summarize
=> Add tf-summarize

README.md
=> Updated Scalr description in the README.md 

README.md
Hi,
Stjepan from manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Bootstrapping Microservices, 2nd Ed

README.md
=> Add OTF (Open Terraforming Framework)

README.md
added a blog post on cloud cost management using Infracost, Terraform, and GitHub Actions.
=> Add "How to use Infracost as the guardrail to manage cloud cost during Terraform development"

README.md
https://github.com/busser/tftree
=> tools: add tftree

README.md
Add ressources:
- azapi and azdevops providers 
- Update the aztfexport details
=> Added azapi and azdevops provider

README.md
Hi, I added Terraform security guide.
=> Added Terraform Security Guide

README.md
- Add the `terraformsh` tool
- Add a missing '-' before a neighboring tool description
=> Add entry for tool `terraformsh`

README.md
https://github.com/bschaatsbergen/terraform-gce-atlantis
cc: @bschaatsbergen
=> Add terraform-gce-atlantis

README.md
https://github.com/paololazzari/terraform-repl
=> Add terraform-repl

README.md
=> Add fuzzy-terraform-rm

README.md
https://github.com/datarootsio/tf-profile/
=> Add tf-profile

README.md
Added some features for Terrareg
I hope this looks okay :)
Many thanks!
=> Add additional features for Terrareg

README.md
Small fix for terrakube link documentation
=> Fix Terrakube Link

README.md
Close #221
- Add tfgpt
- Add tfvar
=> Add tfgpt and tfvar

README.md
Unique tool that adds enterprise-style features for folks that already managing Terraform workflows and state using open-source tooling.
=> Add OSS cloud-concierge

README.md
Add Terraform Book written in Korean
=> books : Add Terraform Book written in Korean

README.md
Add Stack-Lifecycle-Deployment
=> Terraform Cloud: Stack-Lifecycle-Deployment

README.md
=> Added book "Terraform for Ops"

README.md
after #240 
- https://github.blog/2022-06-08-sunsetting-atom/
=> remove atom plugin

README.md
Hi,
Stjepan here from Manning. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Terraform in Depth

README.md
=> README: fix hyperlinks

README.md
followup #246
(This would prevent accidental dup submission in the future)
=> books: sort the entries

README.md
- https://github.com/antonbabenko/terraform-best-practices/pull/54
=> tools: add asdf-hashicorp plugin

README.md
[Lynx](https://github.com/clivern/lynx) is a Fast, Secure and Reliable Terraform Backend. It is built in Elixir with Phoenix framework.
It has many features so far:
- **Simplified Setup:** Easy installation and maintenance for hassle-free usage.
- **Team Collaboration:** Manage multiple teams and users seamlessly.
- **User-Friendly Interface:** Enjoy a visually appealing dashboard for intuitive navigation.
- **Project Flexibility:** Support for multiple projects within each team.
- **Environment Management:** Create and manage multiple environments per project.
- **State Versioning:** Keep track of Terraform state versions for better control.
- **Rollback Capability:** Easily revert to previous states for efficient infrastructure management.
- **Terraform Locking Support:** The project …
=> Add lynx, a self hosted terraform backend

README.md
Adds [pug](https://github.com/leg100/pug) to the tools section.
=> tools: add pug

README.md
A free and complete Terraform course in French covering fundamentals, advanced usage, and real-world examples.
=> Add French Blog

README.md
Add Terraform Academy Learning App to new Apps and Learning section.
=> Add Terraform Academy Learning App
