README.md
Link to new Terraform Provider for Keycloak
=> Add Link - Terraform Provider Keycloak 

README.md
`terraform-bundle` is super helpful when building Docker images for CI runs. It's not very well publicized so I figured I would add it here.
=> Add terraform-bundle to readme

README.md
A provider that aims to solve the problem of how to securely provision Vault secrets via Terraform.
=> Add `sumup-oss/terraform-provider-vaulted`

README.md
This PR adds the `xterrafile` tool which can help manage Terraform modules in different way with concurrent downloads of modules and the `terraform-digitalocean-droplet` module which manages all the resources that are related to Droplet management and implementation.
=> Add `xterrafile` tool and `terraform-digitalocean-droplet` module

README.md
Hi there, I'd like to add [para](https://github.com/paraterraform/para), my OSS project, to the list of tools.
Para can automatically download 3rd-party plugins and even Terraform and Terragrunt themselves.
=> Add para to the list of tools

README.md
I wrote a small tool which updates version constraints in your Terraform configurations.
https://github.com/minamijoyo/tfupdate
Features:
- Update version constraints of Terraform core and providers
- Update all your Terraform configurations recursively under a given directory
- Get the latest release version automatically from GitHub Release
- Terraform v0.12+ support
I would appreciate it if you could add it to the Tools list.
=> Add tfupdate to Tools list

README.md
This updates the description of terragrunt, as the current one is a bit out of date. terragrunt has moved on quite a bit from the days it only provided locking support (in fact, that is supported by terraform natively).
=> Update terragrunt description

README.md
Terraform Visual is a powerful tool I've been working on recently as a side project.
Currently it's able to visualize your Terraform plan and only render changed resources without distracting you with the whole complicated infrastructure hierarchy that you maintain.
The ultimate goal is make it CI/CD friendly so any team using CI/CD can integrate with it easily and benefit from the visualization to spot unwanted infrastructure changes right away
* GitHub: https://github.com/hieven/terraform-visual
* Website: https://hieven.github.io/terraform-visual/
=> Add Terraform Visual to tools

README.md
A production need for a graphql terraform provider arose, so I developed this provider to make it possible to manage graphql api resources. At this time it is the only graphql provider available, and I think others who need to automate graphql api resources will find this tool useful and full featured.
=> add terraform-provider-graphql

README.md
I wrote a command line editor for HCL
https://github.com/minamijoyo/hcledit
Features:
- CLI-friendly: Read HCL from stdin, edit and write to stdout, easily pipe and combine other commands
- Keep comments: You can update lots of existing HCL files with automation scripts
- Schemaless: independent of specific HCL applications
- HCL2 support (not HCL1)
I believe it's useful for Terraform folks.
Thanks!
=> Add hcledit to Tools list

README.md
Hey.
I work for [env0](https://www.env0.com/) and am the author of [Terratag](https://github.com/env0/terratag), a CLI tool that enables users of Terraform to automatically create and maintain tags across their entire set of AWS, Azure, and GCP resources.  
Maintaining tags across your application is hard, especially when done manually. Terratag enables you to easily add tags to your existing IaC and benefit from some cross-resource tag applications you wish you had thought of when you had just started writing your Terraform, saving you tons of time and making future updates easy.
=> Add Terratag

README.md
* Add Terraspace to the tools section
* Terraspace is a Terraform Framework
* Blog Post: [Introducing Terraspace: The Terraform Framework](https://blog.boltops.com/2020/08/22/introducing-terraspace-the-terraform-framework)
* Docs: https://terraspace.cloud/
* Repo: https://github.com/boltops-tools/terraspace
=> Add Terraspace

README.md
Hi, I’m author of tfschema, tfupdate, and hcledit.
I’ll share my new project: tfmigrate, which brings you to a new paradigm: Terraform state operation as Code.
Features:
- GitOps friendly: Write terraform state mv/rm/import commands in HCL, plan and apply it.
- Monorepo style support: Move resources to other tfstates to split and merge easily for refactoring.
- Dry run migration: Simulate state operations with a temporary local tfstate and check to see if terraform plan has no changes after the migration without updating remote tfstate.
https://github.com/minamijoyo/tfmigrate
=> Add tfmigrate to Tools list

README.md
Previously Terraform github action repo used to be on link https://github.com/hashicorp/terraform-github-actions
But now this repository is no longer actively developed or maintained so I have updated the new link as https://github.com/hashicorp/setup-terraform
A message from previous repo
This hashicorp/terraform-github-actions repository is no longer actively developed or maintained. It has been superseded by the hashicorp/setup-terraform GitHub action.
=> Just a link updated to newer url

README.md
Adding the official Terraform provider for Rancher v2 to the list.
=> Add Rancher v2 TF provider.

README.md
Update the link to the DataDog provider.
The official Hashicorp-supported project moved to the DataDog organization according to the current project's README.
=> Update DataDog provider link

README.md
This registry https://github.com/philips-labs/terraform-registry allows serving terraform providers published in GitHub releases.
=> Add one more terraform provider registry

README.md
> Welcome to the HashiCorp Terraform mailing list. As of July 22, 2021 inbound messages to this group have been disabled, and it will now be used for outbound announcements only.
>
> Please direct questions and conversations to our primary medium to communicate with practitioners: HashiCorp Discuss. There you can ask questions, engage with the community, share your stories, and interact with Terraform developers.
>
> For more information about Terraform, please see the website at https://www.terraform.io/.
=> docs: replace terraform google groups with terraform discuss

README.md
Hi, Thanks for your awesome List.
I would lie to add the Tool "terraform-state-mover" to the tools section. It is a Handy tool that makes moving State a lot easier, It is for those "one time" Jobs where you will have to repair lot's of state Drift introduced by Outside forse by i.E. your Platform Provider.
I Really like it, and missed it on the List!
Thanks again!
Greetings
^C
=> add terraform-state-mover

README.md
As such modulehub should serve as alternative to official repository, included only in EE list can be misleading
=> Add modulehub to module registries

README.md
This pull request fixes the link formatting for `prettyplan` by removing an extraneous space between `]` and `(`.
=> fix: fix link for prettyplan

README.md
Propose to add terraform module that creates infrastructure on Google cloud for 10$ a month or less.
Useful for hobbyists, students or testing cloud native tools e.g. cert-manager, traefik e.t.c
The entire project can be run inside Google CloudShell and includes an interactive tutorial so may be included in the **Beginner** section or the **How To** section.
@shuaibiyy @davewongillies @antonbabenko
=> how-to: add Google Cloud on a budget using terraform

README.md
Terustry is an opensoure terraform provider registry written in rust.
It's acting as a proxy to gitlab or github releases, and is driven by a yml file
=> registry(provider): add terustry

README.md
Markdown was not properly used causing the layout to not be shown as the intended list.
=> fix: align Google Cloud section

README.md
* tfsec: https://github.com/tfsec/tfsec is redirected to https://github.com/aquasecurity/tfsec
* tflint: https://github.com/wata727/tflint is redirected to https://github.com/terraform-linters/tflint
* terraform-docs: https://github.com/segmentio/terraform-docs is redirected to https://github.com/terraform-docs/terraform-docs
* terrascan: https://github.com/cesar-rodriguez/terrascan is redirected to https://github.com/accurics/terrascan
=> fix: update links to some tools

README.md
ValidIaC is a new open-source tool that combines several open-source projects and tools to allow developers to check their Terraform HCL (stay tuned for more IaC tools in the near future) code without changing context and from within the same workflow. ValidIaC integrates four popular tools for Terraform to bring the combined value of each tool:
Lint -  tflint, A Pluggable Terraform Linter that finds possible errors (like illegal instance types) and warns about deprecated syntax and unused declarations
Security -  tfsec uses static analysis of your Terraform templates to spot potential security issues.
Cost -  infracost, shows cloud cost estimates for Terraform, before making changes to the cloud.
Mapping -  inframap reads your tfstate or HCL to generate a graph specific for each …
=> tools: add validiac

README.md
Tapir is a private Terraform registry with both modules and provider support
=> Include Tapir

README.md
Digger (https://digger.dev/) is an Open Source alternative to Terraform cloud - added it under alternative to Terraform Enterprise in the list.
=> Added Digger as a Terraform Cloud Alternative

README.md
Hi, I've created Terraform CLI tool, tftarget which is Terraform command wrapper.
The use case is for a multi-person development team. By using tftarget, you can easily perform `terraform xxx -target={...}`. Of course, it is not recommended to use `terraform xxx -target={...}` as a basic operation in production environments, but we recognize that there are times when the target option must be used.
Features:
You can interactively select a resource to (plan | apply | destroy) with the target option.
https://github.com/future-architect/tftarget
=> Add tftarget to Tools list

README.md
Add a new vendor supported provider, terraform-provider-artifactory, to the README.md file. The provider is for JFrog Artifactory and can be found at the given link.
=> Add terraform-provider-artifactory

README.md
https://github.com/suzuki-shunsuke/tfprovidercheck
tfprovidercheck is a command line tool for security.
It prevents malicious Terraform Providers from being executed.
You can define the allow list of Terraform Providers and their versions, and check if disallowed providers aren't used.
=> Add tfprovidercheck

README.md
Whenever you need to dynamically work with AWS accounts this is pretty handy.
=> Added terraform-aws-account-lookup module

README.md
[Coder](https://coder.com) enables organizations to set up development environments in their public or private cloud infrastructure. Cloud development environments are defined with Terraform, connected through a secure high-speed Wireguard® tunnel, and are automatically shut down when not in use to save on costs. Coder gives engineering teams the flexibility to use the cloud for workloads that are most beneficial to them.
- Define cloud development environments in Terraform
- EC2 VMs, Kubernetes Pods, Docker Containers, etc.
- Automatically shutdown idle resources to save on costs
- Onboard developers in seconds instead of days
=> add terraform-provider-coder

README.md
A command line utility to facilitate terraforming your existing Cloudflare resources, it facilitates importing all existing cf resources like DNS records. waf acls, we run in the prod, the tool seems stable enough. and I thought why not contribute here, you guys are doing amazing job :D keep it up 👍🏻
=> tools: add cf-terraforming

README.md
Found some abandoned or archived tools.
This doesn't imply that everything else is not abandoned, just updating those that I checked.
https://github.com/coretech/terrafile - has been archived by the owner on Mar 19, 2024
https://github.com/snyk/driftctl - "This project is now in maintenance mode. We cannot promise to review contributions. Please feel free to fork the project to apply any changes you might want to make."
https://github.com/gaia-app/gaia - no updates for 2 years, discord is abandoned
https://github.com/raymondbutcher/pretf - no updates for 3 years, yet @raymondbutcher is active on GitHub. Maybe it's too early, but worth considering.
https://github.com/naorlivne/terraformize - has been archived by the owner on Sep 4, 2023
Feel free to edit the PR if you feel like changes are …
=> tools: mark several projects as abandoned

README.md
Terralist is a self-hosted private registry I created a while back and IMO it matured enough to be included in this list.
=> Add Terralist to the Self-Hosted Registries list

README.md
This PR propose the addition of the `terraform-provider-uname` (https://github.com/julienlevasseur/terraform-provider-uname) to the list of Community Providers.
=> Add terraform-provider-uname to the list of Community Providers

README.md
Library.tf is a website that provides information on the Terraform and OpenTofu registries in one place.
=> Adding library.tf to the list

README.md
This PR adds `terraform-provider-proxmox`( https://github.com/Telmate/terraform-provider-proxmox ) to the list of community providers.
=> add terraform-provider-proxmox

README.md
A product by this team still exists, but it has nothing to do with terraform
=> Mark hatchet as being abandoned

README.md
This pull request adds TerraForce to the Tools section of awesome-terraform. TerraForce is a policy enforcement tool for Terraform that helps teams maintain consistency and compliance through lifecycle policy checks, flexible policy definitions using Go templates and YAML and seamless CI/CD integration.
Entry added:
- [TerraForce](https://terraforce.henrybravo.nl) - A policy enforcement tool for Terraform that ensures consistency and compliance through lifecycle policy checks, flexible policy definitions, CI/CD integration, and built-in testing.
Please let me know if any changes are needed!
=> Add TerraForce to Tools Section
